language: node_js
sudo: required
node_js: stable
before_script:
  - yarn
  - yarn global add npx
  - npx bower i
cache:
  yarn: true
  directories:
    - node_modules
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm test
dist: trusty
